<?php
/**
 * Tools → SML Export: one ZIP with everything an engineer needs to audit the
 * site without database access — every WPCode snippet (the groups engine lives
 * there), the plugin list with active flags, source of the active SML plugins,
 * mu-plugins, CREATE TABLE statements for sml_* tables, sml_* options (values
 * of anything that looks like a secret are left out), and the REST namespaces.
 *
 * Administrators only. Read-only: it never changes anything.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

add_action( 'admin_menu', static function () {
	add_management_page( 'SML Export', 'SML Export', 'manage_options', 'sml-hub-export', 'sml_hub_export_page' );
} );

function sml_hub_export_counts() {
	global $wpdb;
	$snips = (int) $wpdb->get_var( "SELECT COUNT(*) FROM {$wpdb->posts} WHERE post_type='wpcode'" );
	require_once ABSPATH . 'wp-admin/includes/plugin.php';
	$plugins = get_plugins();
	$tables  = (array) $wpdb->get_col( $wpdb->prepare( 'SHOW TABLES LIKE %s', $wpdb->esc_like( $wpdb->prefix . 'sml_' ) . '%' ) );
	$mu      = ( defined( 'WPMU_PLUGIN_DIR' ) && is_dir( WPMU_PLUGIN_DIR ) ) ? count( (array) glob( WPMU_PLUGIN_DIR . '/*.php' ) ) : 0;
	return array( 'snippets' => $snips, 'plugins' => count( $plugins ), 'active' => count( (array) get_option( 'active_plugins', array() ) ), 'tables' => count( $tables ), 'mu' => $mu );
}

function sml_hub_export_page() {
	if ( ! current_user_can( 'manage_options' ) ) {
		return;
	}
	$c = sml_hub_export_counts();
	echo '<div class="wrap"><h1>SML Export</h1>';
	echo '<p>Builds one ZIP with the site\'s WPCode snippets (' . (int) $c['snippets'] . '), the plugin list (' . (int) $c['plugins'] . ' installed, ' . (int) $c['active'] . ' active) with source of the active StockMarketLoop plugins, mu-plugins (' . (int) $c['mu'] . '), CREATE TABLE statements for ' . (int) $c['tables'] . ' <code>sml_*</code> tables, and non-secret <code>sml_*</code> options. Nothing is changed.</p>';
	echo '<p>Options whose names contain secret, token, key, password, auth or hash are listed by name only. Snippets and plugin source are exported as-is, so open the ZIP before sharing it if a snippet contains a hard-coded credential.</p>';
	echo '<form method="post" action="' . esc_url( admin_url( 'admin-post.php' ) ) . '">';
	wp_nonce_field( 'sml_hub_export' );
	echo '<input type="hidden" name="action" value="sml_hub_export">';
	echo '<label><input type="checkbox" name="all_plugins" value="1"> Include source of every active plugin (not only StockMarketLoop ones)</label><br><br>';
	submit_button( 'Download export ZIP', 'primary', 'submit', false );
	echo '</form></div>';
}

function sml_hub_export_is_text( $file ) {
	return (bool) preg_match( '/\.(php|js|css|json|md|txt|html|htm|sql|xml|svg|csv)$/i', $file );
}

function sml_hub_export_add_dir( ZipArchive $zip, $dir, $prefix, &$budget ) {
	$dir = rtrim( $dir, '/' );
	if ( ! is_dir( $dir ) ) {
		return;
	}
	$it = new RecursiveIteratorIterator( new RecursiveDirectoryIterator( $dir, FilesystemIterator::SKIP_DOTS ) );
	foreach ( $it as $file ) {
		$path = $file->getPathname();
		if ( ! $file->isFile() || ! sml_hub_export_is_text( $path ) || false !== strpos( $path, '/node_modules/' ) || false !== strpos( $path, '/vendor/' ) ) {
			continue;
		}
		$size = $file->getSize();
		if ( $size > 2 * MB_IN_BYTES || $budget - $size < 0 ) {
			continue;
		}
		$budget -= $size;
		$zip->addFile( $path, $prefix . '/' . ltrim( substr( $path, strlen( $dir ) ), '/' ) );
	}
}

add_action( 'admin_post_sml_hub_export', static function () {
	if ( ! current_user_can( 'manage_options' ) ) {
		wp_die( 'Administrators only.' );
	}
	check_admin_referer( 'sml_hub_export' );
	if ( ! class_exists( 'ZipArchive' ) ) {
		wp_die( 'ZipArchive is not available on this server.' );
	}
	global $wpdb;
	@set_time_limit( 300 );
	$tmp = wp_tempnam( 'sml-export.zip' );
	$zip = new ZipArchive();
	if ( true !== $zip->open( $tmp, ZipArchive::CREATE | ZipArchive::OVERWRITE ) ) {
		wp_die( 'Could not create the ZIP.' );
	}
	$budget = 150 * MB_IN_BYTES;
	$stamp  = gmdate( 'Y-m-d\TH-i-s\Z' );
	$zip->addFromString( 'README.txt', "StockMarketLoop site export $stamp\nSite: " . home_url() . "\nGenerated by SML Group Settings Hub " . SML_HUB_VERSION . "\n\nwpcode/       WPCode snippets (active/ and inactive/), one PHP file each, header comment carries the WPCode settings\nplugins.json  every installed plugin with active flag\nplugins/      source of active StockMarketLoop plugins\nmu-plugins/   must-use plugins\nschema/       CREATE TABLE for sml_* tables\noptions/      sml_* options (secrets by name only)\nrest/         REST namespaces\n" );

	// WPCode snippets.
	$index = array();
	$posts = (array) $wpdb->get_results( "SELECT ID, post_title, post_name, post_status, post_content, post_modified_gmt FROM {$wpdb->posts} WHERE post_type='wpcode' ORDER BY ID ASC", ARRAY_A );
	foreach ( $posts as $p ) {
		$meta = array();
		foreach ( (array) get_post_meta( (int) $p['ID'] ) as $k => $v ) {
			if ( 0 === strpos( $k, '_wpcode_' ) ) {
				$meta[ $k ] = maybe_unserialize( $v[0] );
			}
		}
		$type   = (string) ( $meta['_wpcode_code_type'] ?? 'php' );
		$state  = 'publish' === $p['post_status'] ? 'active' : 'inactive';
		$slug   = sanitize_title( $p['post_title'] ) ?: ( 'snippet-' . $p['ID'] );
		$ext    = in_array( $type, array( 'php', 'js', 'css', 'html', 'text' ), true ) ? ( 'text' === $type ? 'txt' : $type ) : 'txt';
		$header = "/* WPCode snippet #{$p['ID']} \"{$p['post_title']}\" | status: {$p['post_status']} | type: {$type} | location: " . (string) ( $meta['_wpcode_location'] ?? '' ) . ' | auto_insert: ' . (string) ( $meta['_wpcode_auto_insert'] ?? '' ) . ' | priority: ' . (string) ( $meta['_wpcode_priority'] ?? '' ) . " | modified: {$p['post_modified_gmt']} */\n";
		$zip->addFromString( "wpcode/{$state}/{$p['ID']}-{$slug}.{$ext}", $header . $p['post_content'] );
		$index[] = array( 'id' => (int) $p['ID'], 'title' => $p['post_title'], 'status' => $p['post_status'], 'type' => $type, 'location' => $meta['_wpcode_location'] ?? '', 'priority' => $meta['_wpcode_priority'] ?? '', 'bytes' => strlen( (string) $p['post_content'] ), 'modified' => $p['post_modified_gmt'] );
	}
	$zip->addFromString( 'wpcode/index.json', wp_json_encode( $index, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES ) );

	// Plugins.
	require_once ABSPATH . 'wp-admin/includes/plugin.php';
	$active  = array_fill_keys( (array) get_option( 'active_plugins', array() ), true );
	$plugins = array();
	$all     = ! empty( $_POST['all_plugins'] );
	foreach ( get_plugins() as $file => $info ) {
		$dir       = dirname( $file );
		$is_active = isset( $active[ $file ] );
		$plugins[] = array( 'file' => $file, 'name' => $info['Name'], 'version' => $info['Version'], 'active' => $is_active, 'description' => $info['Description'] );
		if ( $is_active && '.' !== $dir && ( $all || preg_match( '/sml|stockmarketloop|channel-admin|group|loop/i', $dir . ' ' . $info['Name'] ) ) ) {
			sml_hub_export_add_dir( $zip, WP_PLUGIN_DIR . '/' . $dir, 'plugins/' . $dir, $budget );
		} elseif ( $is_active && '.' === $dir ) {
			$zip->addFile( WP_PLUGIN_DIR . '/' . $file, 'plugins/' . $file );
		}
	}
	$zip->addFromString( 'plugins.json', wp_json_encode( $plugins, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES ) );
	if ( defined( 'WPMU_PLUGIN_DIR' ) ) {
		sml_hub_export_add_dir( $zip, WPMU_PLUGIN_DIR, 'mu-plugins', $budget );
	}

	// Schema.
	$sql = '';
	foreach ( (array) $wpdb->get_col( $wpdb->prepare( 'SHOW TABLES LIKE %s', $wpdb->esc_like( $wpdb->prefix . 'sml_' ) . '%' ) ) as $table ) {
		$row  = $wpdb->get_row( "SHOW CREATE TABLE `{$table}`", ARRAY_N );
		$n    = (int) $wpdb->get_var( "SELECT COUNT(*) FROM `{$table}`" );
		$sql .= "-- {$table} ({$n} rows)\n" . ( $row ? $row[1] : '' ) . ";\n\n";
	}
	$zip->addFromString( 'schema/sml-tables.sql', $sql );

	// Options (secrets by name only).
	$opts = array();
	foreach ( (array) $wpdb->get_results( $wpdb->prepare( "SELECT option_name, option_value FROM {$wpdb->options} WHERE option_name LIKE %s ORDER BY option_name", $wpdb->esc_like( 'sml_' ) . '%' ), ARRAY_A ) as $o ) {
		$name = $o['option_name'];
		if ( preg_match( '/secret|token|key|password|passwd|auth|hash|nonce|credential/i', $name ) ) {
			$opts[ $name ] = '[redacted by name]';
			continue;
		}
		$val = maybe_unserialize( $o['option_value'] );
		$enc = wp_json_encode( $val );
		$opts[ $name ] = strlen( (string) $enc ) > 20000 ? '[' . strlen( (string) $enc ) . ' bytes, truncated]' : $val;
	}
	$zip->addFromString( 'options/sml-options.json', wp_json_encode( $opts, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES ) );
	$zip->addFromString( 'rest/namespaces.json', wp_json_encode( function_exists( 'rest_get_server' ) ? rest_get_server()->get_namespaces() : array(), JSON_PRETTY_PRINT ) );
	$zip->close();

	nocache_headers();
	header( 'Content-Type: application/zip' );
	header( 'Content-Disposition: attachment; filename="sml-site-export-' . $stamp . '.zip"' );
	header( 'Content-Length: ' . filesize( $tmp ) );
	readfile( $tmp );
	@unlink( $tmp );
	exit;
} );
