-- Module 0 ("Start Here") is a real Academy module. Migration 019 required
-- module ids above zero, so every Start Here progress save was rejected by
-- Postgres. Allow zero, and start new students at the Start Here track.
-- Existing students keep their current position.
--
-- The 019 checks were declared inline, so their names were generated by
-- Postgres. They are found by definition rather than by an assumed name, so
-- this cannot silently leave the old "> 0" check in place.

BEGIN;

DO $migrate$
DECLARE
  target RECORD;
  found RECORD;
BEGIN
  FOR target IN SELECT * FROM (VALUES
    ('academy_students', 'current_module'),
    ('academy_progress', 'module_id'),
    ('academy_content',  'module_id'),
    ('academy_quizzes',  'module_id')
  ) AS t(tbl, col) LOOP
    FOR found IN
      SELECT conname FROM pg_constraint
      WHERE contype = 'c'
        AND conrelid = target.tbl::regclass
        AND pg_get_constraintdef(oid) = format('CHECK ((%s > 0))', target.col)
    LOOP
      EXECUTE format('ALTER TABLE %I DROP CONSTRAINT %I', target.tbl, found.conname);
    END LOOP;
    IF EXISTS (
      SELECT 1 FROM pg_constraint
      WHERE contype = 'c' AND conrelid = target.tbl::regclass
        AND pg_get_constraintdef(oid) LIKE format('%%(%s > 0)%%', target.col)
    ) THEN
      RAISE EXCEPTION 'a "% > 0" check remains on %', target.col, target.tbl;
    END IF;
    EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I CHECK (%I >= 0)',
      target.tbl, target.tbl || '_' || target.col || '_nonnegative', target.col);
  END LOOP;
END
$migrate$;

ALTER TABLE academy_students ALTER COLUMN current_module SET DEFAULT 0;

COMMIT;
